DROP TABLE IF EXISTS `question`;
CREATE TABLE `question` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(50) DEFAULT NULL,
  `DESCRIPTION` text,
  `GMT_CREATE` bigint(20) DEFAULT NULL,
  `GMT_MODIFIED` bigint(20) DEFAULT NULL,
  `CREATOR` bigint(20) DEFAULT NULL,
  `COMMENT_COUNT` int(11) DEFAULT '0',
  `VIEW_COUNT` int(11) NOT NULL DEFAULT '0',
  `LIKE_COUNT` int(11) DEFAULT '0',
  `TAG` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`)
)