DROP TABLE IF EXISTS `notification`;
CREATE TABLE `notification` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOTIFIER` bigint(20) DEFAULT NULL,
  `RECEIVER` bigint(20) DEFAULT NULL,
  `OUTERID` bigint(20) DEFAULT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `GMT_CREATE` bigint(20) DEFAULT NULL,
  `STATUS` int(11) DEFAULT '0',
  `NOTIFIER_NAME` varchar(100) DEFAULT NULL,
  `OUTER_TITLE` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`)
)